Repository HashLoad/horse, pull requests merged in 2020-06, with the labels that each got.

#39 resolved: #30
  src/Horse.Core.pas
Labels: bug

#40 Improved exception handling and code improvement
  src/Horse.Router.pas
Labels: bug, enhancement

#41 resolved: #26
  src/Horse.Router.pas
Labels: bug

#43 Improvement Router Method
  src/Horse.Core.Route.Intf.pas
  src/Horse.Core.Route.pas
  src/Horse.Core.pas
Labels: enhancement
